### ISSUE TITLE
Use cmake for entire installation 

### ISSUE THREAD

**Issue by ErichZimmer** [ErichZimmer/OpenPIV-Python-cxx#10]
CircleCI has an issue building openpivcore/libopenivcore because the library path created in setup.py is wrong. This issue could be solved by using a pure cmake installation, however, I am not sure if this is the correct way to go.

**Comment by ErichZimmer** [comment]
It appears that the submodule is not found entirely for some reason...

**Comment by ErichZimmer** [comment]
The output
```
Warning: could not locate _libs folder.
Creating _libs folder and libraries
Could not locate cmake build folder. Building openpivcore
CMake Error: The source directory "/home/circleci/repo/extern/openpiv-c--qt/ ." does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    main()
  File "setup.py", line 24, in main
    build_openpivcore(openpiv_cxx_dir, _libs_path)
  File "/home/circleci/repo/openpiv_cxx/_build_utilities/build_libs.py", line 30, in build_openpivcore
    subprocess.check_call(cmake_args, cwd = openpiv_cxx_dir)
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-S .', '-B build', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

Exited with code exit status 1

CircleCI received exit code 1
```
points to the directory `"/home/circleci/repo/extern/openpiv-c--qt/ ."`. The last three indexes of the directory string, `"/ ."`, might be the problem.

**Comment by ErichZimmer** [comment]
Fixed by changing CI to GitHub actions.

**Comment by ErichZimmer** [comment]
To avoid some issues, we should use cmake with multiple `project()`s to avoid using python for compiling c++ binaries. In theory, this should allow better control of vcpkg and better cross compilation.
